import 'element-plus/dist/index.css';
import 'virtual:uno.css';
import '@/assets/css-vars.css';
import 'virtual:svg-icons-register';
import 'animate.css';
import '@/components/mt-edit/assets/css/custom_ani.css';
import MtDzr from '@/components/mt-dzr';
import MtEdit from '@/components/mt-edit';
import MtPreview from '@/components/mt-preview';
import { leftAsideStore } from '@/components/mt-edit/store/left-aside';
export { MtDzr, MtEdit, MtPreview, leftAsideStore };
